frr defaults traditional
hostname GF_B
service integrated-vtysh-config
!
interface s1
 ip address 10.200.1.254/24
exit
!
interface s2
 ip address 10.200.2.254/24
exit
!
interface mgmt
 ip address 172.30.119.20/24
exit
!
line vty
!
