connections {
 msc {
  version = 2
  local_addrs = 10.200.2.2
  remote_addrs = 10.100.2.2
  proposals = aes256gcm16-prfsha384-ecp384
  reauth_time = 3h
  rekey_time = 0s
  over_time = 10m
  dpd_delay = 10s
  keyingtries = 0
  mobike = no
  local {
   auth = pubkey
   certs = cert.pem
   id = I_B2.msc.test
  }
  remote {
   auth = pubkey
   id = I_A2.msc.test
   cacerts = ca.pem
   revocation = strict
  }
  children {
   protected {
    local_ts = 10.2.2.0/24
    remote_ts = 10.1.2.0/24
    mode = tunnel
    reqid = 102
    esp_proposals = aes256gcm16-ecp384
    rekey_time = 50m
    life_time = 1h
    start_action = trap
    dpd_action = trap
    close_action = trap
   }
  }
 }
}
