frr defaults traditional
hostname BLACK
service integrated-vtysh-config
!
interface p11
 ip address 172.21.11.2/30
 ip ospf area 0
 ip ospf network point-to-point
 ip ospf hello-interval 1
 ip ospf dead-interval 4
exit
!
interface p12
 ip address 172.21.12.2/30
 ip ospf area 0
 ip ospf network point-to-point
 ip ospf hello-interval 1
 ip ospf dead-interval 4
exit
!
interface p21
 ip address 172.21.21.2/30
 ip ospf area 0
 ip ospf network point-to-point
 ip ospf hello-interval 1
 ip ospf dead-interval 4
exit
!
interface p22
 ip address 172.21.22.2/30
 ip ospf area 0
 ip ospf network point-to-point
 ip ospf hello-interval 1
 ip ospf dead-interval 4
exit
!
router ospf
 ospf router-id 172.21.11.2
 passive-interface default
 no passive-interface p11
 no passive-interface p12
 no passive-interface p21
 no passive-interface p22
exit
!
line vty
!
