frr defaults traditional
hostname GF_A
service integrated-vtysh-config
!
interface s1
 ip address 10.100.1.254/24
exit
!
interface s2
 ip address 10.100.2.254/24
exit
!
interface mgmt
 ip address 172.30.109.20/24
exit
!
line vty
!
