Building configuration...

Current configuration:
!
frr version 10.0
frr defaults traditional
hostname black
no ipv6 forwarding
service integrated-vtysh-config
!
interface p11
 ip address 172.21.11.2/30
 ip ospf area 0
 ip ospf dead-interval 4
 ip ospf hello-interval 1
 ip ospf network point-to-point
 no ip ospf passive
exit
!
interface p12
 ip address 172.21.12.2/30
 ip ospf area 0
 ip ospf dead-interval 4
 ip ospf hello-interval 1
 ip ospf network point-to-point
 no ip ospf passive
exit
!
interface p21
 ip address 172.21.21.2/30
 ip ospf area 0
 ip ospf dead-interval 4
 ip ospf hello-interval 1
 ip ospf network point-to-point
 no ip ospf passive
exit
!
interface p22
 ip address 172.21.22.2/30
 ip ospf area 0
 ip ospf dead-interval 4
 ip ospf hello-interval 1
 ip ospf network point-to-point
 no ip ospf passive
exit
!
router ospf
 ospf router-id 172.21.11.2
 passive-interface default
exit
!
end
