frr defaults traditional
hostname OF_A1
service integrated-vtysh-config
!
interface outside
 ip address 172.21.11.1/30
 ip ospf area 0
 ip ospf network point-to-point
 ip ospf hello-interval 1
 ip ospf dead-interval 4
exit
!
interface inside
 ip address 172.20.11.2/30
 ip ospf area 0
exit
!
interface mgmt
 ip address 172.30.109.23/24
exit
!
router ospf
 ospf router-id 172.21.11.1
 passive-interface default
 no passive-interface outside
exit
!
line vty
!
