Building configuration...

Current configuration:
!
frr version 10.0
frr defaults traditional
hostname of-a1
no ipv6 forwarding
service integrated-vtysh-config
!
interface inside
 ip address 172.20.11.2/30
 ip ospf area 0
exit
!
interface mgmt
 ip address 172.30.109.23/24
exit
!
interface outside
 ip address 172.21.11.1/30
 ip ospf area 0
 ip ospf dead-interval 4
 ip ospf hello-interval 1
 ip ospf network point-to-point
 no ip ospf passive
exit
!
router ospf
 ospf router-id 172.21.11.1
 passive-interface default
exit
!
end
